@startuml
'https://plantuml.com/class-diagram

abstract class TienDienBacThang{
    String tenBac
    int min, max, gia
    + {abstract} TienDienBacThang keTiep (TienDienBacThang k)
    + {abstract} int  tinhTienDien(int soKW)
}
TienDienBacThang <|-- BacCaoNhat
TienDienBacThang <|-- BacBinhThuong
TienDienBacThang <-- BacBinhThuong: keTiep

note bottom of BacBinhThuong
    Phương thức tính:
        Nếu soKW < max: trả về (soKW - min) * gia
        Ngược lại: trả về ((max - min)*gia + tiền điện bậc kế tiếp)

end note

@enduml